@startuml

title __LOG121LAB3's Class Diagram__\n

  namespace controller {
    class controller.CommandManager {
    - commands : ArrayList
            {static} - mngr : CommandManager
            {static} + getInstance()
            + redo()
            + undo()
            + reverse()
    }
  }
  

  namespace controller {
    abstract class controller.PerspectiveCommand {
        -receiver : Perspective
        {abstract} +execute()
    }
  }

  namespace controller {
      class controller.DeserializeCommand {

        +execute()
      }
    }

    namespace controller {
          class controller.SerializeCommand {

            +execute()
          }
     }
  

  namespace controller {
    class controller.TranslateCommand {
        +execute()
    }
  }

  namespace controller {
      abstract class controller.ImageCommand {
      -subject : ImageManager
          +execute()
      }
    }
  

  namespace controller {
    class controller.ZoomCommand {
        +execute()
    }
  }
  

  namespace modele {
    class modele.ImageManager {
            - loadPerspectives()
            + loadImage()
            +save()
            +openFromFile
    }
  }
  

  namespace modele {
    class modele.Perspective {
    - image : ImageIO
    - zoom : double
    - translation : Point
        +zoom()
        +translate()
    }
  }
  

    namespace observer {
      interface observer.MyObservable {
          {abstract} + addObserver()
          {abstract} + notifyObservers()
          {abstract} + removeObserver()
      }
    }


    namespace observer {
      interface observer.MyObserver {
          {abstract} + update()
      }
    }
  

  namespace program {
    class program.Program {
    }
  }
  

  namespace view {
    class view.ImageMenu {
    }
  }
  

  namespace view {
    class view.ImagePanel {
        +paint()
    }
  }
  

  namespace view {
    class view.ImageWindow {
    }
  }
  

  namespace view {
    class view.MainPanel {
        -displayMenu
    }
  }
  

  namespace view {
    class view.MainWindow {
    }
  }

  namespace view {
      class view.MainMenu {
      }
  }

  

  controller.PerspectiveCommand -up-|> javax.swing.AbstractAction
  controller.TranslateCommand -up-|> controller.PerspectiveCommand
  controller.ZoomCommand -up-|> controller.PerspectiveCommand
  modele.Perspective .up.|> observer.MyObservable
  view.ImagePanel .up.|> observer.MyObserver
  controller.TranslateCommand -up-> modele.Perspective
  controller.ZoomCommand -up-> modele.Perspective
  controller.PerspectiveCommand -up-> controller.CommandManager
  controller.PerspectiveCommand --o controller.CommandManager
  view.MainWindow .up.> view.MainPanel
  view.MainWindow .up.> view.MainMenu
  view.ImageWindow .up.> view.ImagePanel
  view.ImageWindow .up.> view.ImageMenu
  observer.MyObservable o-- observer.MyObserver
  view.ImagePanel .up.> modele.Perspective
  view.ImageMenu o-- controller.PerspectiveCommand
  view.ImagePanel o-- controller.PerspectiveCommand
  modele.ImageManager --> modele.Perspective
  view.MainMenu -up-> controller.DeserializeCommand
  controller.DeserializeCommand -up-> modele.ImageManager
   controller.DeserializeCommand -up-|> controller.ImageCommand
   controller.SerializeCommand -up-|> controller.ImageCommand
   javax.swing.AbstractAction <|-up- controller.ImageCommand
   controller.SerializeCommand -up-> modele.ImageManager
    view.MainMenu -up-> controller.SerializeCommand

  hide program
  hide javax.swing.JPanel
  hide javax.swing.JFrame

right footer

endfooter

@enduml
